In [1]:
import numpy as np

import pandas as pd

In [2]:
reviews = [review for review in open('Restaurant_Reviews.tsv')]

In [3]:
reviews

['Review\tLiked\n',
 'Wow... Loved this place.\t1\n',
 'Crust is not good.\t0\n',
 'Not tasty and the texture was just nasty.\t0\n',
 'Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.\t1\n',
 'The selection on the menu was great and so were the prices.\t1\n',
 'Now I am getting angry and I want my damn pho.\t0\n',
 "Honeslty it didn't taste THAT fresh.)\t0\n",
 'The potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer.\t0\n',
 'The fries were great too.\t1\n',
 'A great touch.\t1\n',
 'Service was very prompt.\t1\n',
 'Would not go back.\t0\n',
 'The cashier had no care what so ever on what I had to say it still ended up being wayyy overpriced.\t0\n',
 'I tried the Cape Cod ravoli, chicken, with cranberry...mmmm!\t1\n',
 'I was disgusted because I was pretty sure that was human hair.\t0\n',
 'I was shocked because no signs indicate cash only.\t0\n',
 'Highly recommended.\t1\n',
 'Waitress was a

In [4]:
for review_no, review in enumerate(reviews):
    
    print(review_no, review)

0 Review	Liked

1 Wow... Loved this place.	1

2 Crust is not good.	0

3 Not tasty and the texture was just nasty.	0

4 Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.	1

5 The selection on the menu was great and so were the prices.	1

6 Now I am getting angry and I want my damn pho.	0

7 Honeslty it didn't taste THAT fresh.)	0

8 The potatoes were like rubber and you could tell they had been made up ahead of time being kept under a warmer.	0

9 The fries were great too.	1

10 A great touch.	1

11 Service was very prompt.	1

12 Would not go back.	0

13 The cashier had no care what so ever on what I had to say it still ended up being wayyy overpriced.	0

14 I tried the Cape Cod ravoli, chicken, with cranberry...mmmm!	1

15 I was disgusted because I was pretty sure that was human hair.	0

16 I was shocked because no signs indicate cash only.	0

17 Highly recommended.	1

18 Waitress was a little slow in service.	0

19 This place is not worth your tim

733 Nicest Chinese restaurant I've been in a while.	1

734 Overall, I like there food and the service.	1

735 They also now serve Indian naan bread with hummus and some spicy pine nut sauce that was out of this world.	1

736 Probably never coming back, and wouldn't recommend it.	0

737 Friend's pasta -- also bad, he barely touched it.	0

738 Try them in the airport to experience some tasty food and speedy, friendly service.	1

739 I love the decor with the Chinese calligraphy wall paper.	1

740 Never had anything to complain about here.	1

741 The restaurant is very clean and has a family restaurant feel to it.	1

742 It was way over fried.	0

743 I'm not sure how long we stood there but it was long enough for me to begin to feel awkwardly out of place.	0

744 When I opened the sandwich, I was impressed, but not in a good way.	0

745 Will not be back!	0

746 There was a warm feeling with the service and I felt like their guest for a special treat.	1

747 An extensive menu provides lots

In [5]:
data = pd.read_csv('Restaurant_Reviews.tsv', sep = '\t', quoting = 3)

In [6]:
data.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [7]:
import re 

import nltk

from nltk.corpus import stopwords

all_stopwords = stopwords.words('english')

all_stopwords.remove('not')

from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [8]:
corpus = []

In [9]:
for i in range(0, 1000):
    
    review = re.sub('[^A-Za-z]', ' ',data['Review'][i])
    
    review = review.lower()
    
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
    
    review = ' '.join(review)
    
    corpus.append(review)

In [10]:
corpus[:11]

['wow love place',
 'crust not good',
 'not tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price',
 'get angri want damn pho',
 'honeslti tast fresh',
 'potato like rubber could tell made ahead time kept warmer',
 'fri great',
 'great touch',
 'servic prompt']

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features = 1500)

In [12]:
X = cv.fit_transform(corpus).toarray()

y = data['Liked']

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [14]:
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()

classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [15]:
y_pred = classifier.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)

print(cm)

accuracy_score(y_test, y_pred)

[[55 42]
 [12 91]]


0.73

In [19]:
new_review = 'I love this restaurant so much'

new_review = re.sub('[^a-zA-Z]', ' ', new_review)

new_review = new_review.lower()

new_review = new_review.split()

all_stopwords = stopwords.words('english')

all_stopwords.remove('not')

new_review = [ps.stem(word) for word in new_review if not word in set(all_stopwords)]

new_review = ' '.join(new_review)

new_corpus = [new_review]

new_X_test = cv.transform(new_corpus).toarray()

new_y_pred = classifier.predict(new_X_test)

In [20]:
new_y_pred

array([1], dtype=int64)

In [21]:
new_review = 'I hate this restaurant so much'

new_review = re.sub('[^a-zA-Z]', ' ', new_review)

new_review = new_review.lower()

new_review = new_review.split()

all_stopwords = stopwords.words('english')

all_stopwords.remove('not')

new_review = [ps.stem(word) for word in new_review if not word in set(all_stopwords)]

new_review = ' '.join(new_review)

new_corpus = [new_review]

new_X_test = cv.transform(new_corpus).toarray()

new_y_pred = classifier.predict(new_X_test)

In [22]:
new_y_pred

array([0], dtype=int64)